global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts/*.yml"

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the MCP Server
  - job_name: 'mcp-server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mcp-server:3000']

  # Scrape the Coordinator Agent (assuming it exposes metrics)
  - job_name: 'coordinator-agent'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['coordinator-agent:8000']

  # Scrape the Scraper Agent (assuming it exposes metrics)
  - job_name: 'scraper-agent'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['scraper-agent:8001']

  # Scrape the Tagger Agent (assuming it exposes metrics)
  - job_name: 'tagger-agent'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['tagger-agent:8002']

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Pulsar metrics (if available)
  - job_name: 'pulsar'
    static_configs:
      - targets: ['pulsar:8080']

  # Cadvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Additional scrape configs as needed...
